// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// embArrows
arma::mat embArrows(const arma::mat& emb, const arma::sp_mat& tp, double arrowScale, int nthreads);
RcppExport SEXP _dynvelocity_embArrows(SEXP embSEXP, SEXP tpSEXP, SEXP arrowScaleSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type emb(embSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type arrowScale(arrowScaleSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(embArrows(emb, tp, arrowScale, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// colDeltaCorLog10
arma::mat colDeltaCorLog10(const arma::mat& e, const arma::mat& d, const arma::vec& waypoints, double pseudocount, int nthreads);
RcppExport SEXP _dynvelocity_colDeltaCorLog10(SEXP eSEXP, SEXP dSEXP, SEXP waypointsSEXP, SEXP pseudocountSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type waypoints(waypointsSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(colDeltaCorLog10(e, d, waypoints, pseudocount, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynvelocity_embArrows", (DL_FUNC) &_dynvelocity_embArrows, 4},
    {"_dynvelocity_colDeltaCorLog10", (DL_FUNC) &_dynvelocity_colDeltaCorLog10, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynvelocity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
