# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

embArrows <- function(emb, tp, arrowScale = 1.0, nthreads = 1L) {
    .Call('_dynvelocity_embArrows', PACKAGE = 'dynvelocity', emb, tp, arrowScale, nthreads)
}

colDeltaCorLog10 <- function(e, d, waypoints, pseudocount = 1.0, nthreads = 1L) {
    .Call('_dynvelocity_colDeltaCorLog10', PACKAGE = 'dynvelocity', e, d, waypoints, pseudocount, nthreads)
}

